Repository KindaiCVLAB/machinelearning-images, pull requests merged in 2021-12, with the labels that each got.

#29 Update November
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  README.md
Labels: update

#28 Fix bash
  configs/vscode/base.json
  configs/vscode/vscode.json
Labels: bug

#38 Fix docs for cudnn version
  README.md
Labels: documentation

#36 Support optuna
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/build-image/action.yaml
  .github/workflows/cuda10.2-cudnn7.yaml
  .github/workflows/cuda10.2-cudnn8.yaml
  .github/workflows/cuda11.0.3-cudnn8.yaml
  .github/workflows/cuda11.1.1-cudnn8.yaml
  .github/workflows/cuda11.2.0-cudnn8.yaml
  .github/workflows/cuda11.2.1-cudnn8.yaml
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.0-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  .github/workflows/show-version/action.yaml
  .github/workflows/test-version/action.yaml
  Dockerfile
  README.md
  tests/test_cmd.py
  tests/test_import.py
  tests/test_pip.py
Labels: enhancement

#37 Bump cuda version to cuda11.5 using in torch-nightly and torchvision-nightly
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  README.md
Labels: update

#40 Fix actions for cuda11.2.1-cudnn8
  .github/workflows/cuda11.2.1-cudnn8.yaml
Labels: bug

#42 Always install the latest rclone and code-server
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/build-image/action.yaml
  .github/workflows/cuda10.2-cudnn7.yaml
  .github/workflows/cuda10.2-cudnn8.yaml
  .github/workflows/cuda11.0.3-cudnn8.yaml
  .github/workflows/cuda11.1.1-cudnn8.yaml
  .github/workflows/cuda11.2.0-cudnn8.yaml
  .github/workflows/cuda11.2.1-cudnn8.yaml
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.0-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  .github/workflows/show-version/action.yaml
  .github/workflows/test-version/action.yaml
  Dockerfile
  README.md
  tests/test_cmd.py
Labels: improve

#43 Use lts or current nodejs in all images
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/build-image/action.yaml
  .github/workflows/cuda10.2-cudnn7.yaml
  .github/workflows/cuda10.2-cudnn8.yaml
  .github/workflows/cuda11.0.3-cudnn8.yaml
  .github/workflows/cuda11.1.1-cudnn8.yaml
  .github/workflows/cuda11.2.0-cudnn8.yaml
  .github/workflows/cuda11.2.1-cudnn8.yaml
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.0-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  .github/workflows/show-version/action.yaml
  .github/workflows/test-version/action.yaml
  Dockerfile
  README.md
  tests/test_cmd.py
Labels: improve

#44 Stop using pyenv
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/build-image/action.yaml
  .github/workflows/cuda10.2-cudnn7.yaml
  .github/workflows/cuda10.2-cudnn8.yaml
  .github/workflows/cuda11.0.3-cudnn8.yaml
  .github/workflows/cuda11.1.1-cudnn8.yaml
  .github/workflows/cuda11.2.0-cudnn8.yaml
  .github/workflows/cuda11.2.1-cudnn8.yaml
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.0-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  .github/workflows/show-version/action.yaml
  .github/workflows/test-version/action.yaml
  Dockerfile
  README.md
  configs/vscode/container-building.json
  configs/vscode/settings.json
  configs/vscode/vscode.json
  tests/test_cmd.py
Labels: enhancement

#45 Replace torchsummary to torchinfo
  .github/ISSUE_TEMPLATE/update-library.md
  .github/workflows/build-image/action.yaml
  .github/workflows/cuda10.2-cudnn7.yaml
  .github/workflows/cuda10.2-cudnn8.yaml
  .github/workflows/cuda11.0.3-cudnn8.yaml
  .github/workflows/cuda11.1.1-cudnn8.yaml
  .github/workflows/cuda11.2.0-cudnn8.yaml
  .github/workflows/cuda11.2.1-cudnn8.yaml
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.0-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  .github/workflows/show-version/action.yaml
  .github/workflows/test-version/action.yaml
  Dockerfile
  README.md
  tests/test_pip.py
Labels: enhancement

#46 Add new build system
  .github/workflows/build-image.new/action.yaml
  .github/workflows/build-push.yaml
  Dockerfile.new
  versions/common/requirements.txt
  versions/cuda10.2-cudnn7/packages.json
  versions/cuda10.2-cudnn7/requirements.txt
  versions/cuda10.2-cudnn8/packages.json
  versions/cuda10.2-cudnn8/requirements.txt
  versions/cuda11.0.3-cudnn8/packages.json
  versions/cuda11.0.3-cudnn8/requirements.txt
  versions/cuda11.1.1-cudnn8/packages.json
  versions/cuda11.1.1-cudnn8/requirements.txt
  versions/cuda11.2.0-cudnn8/packages.json
  versions/cuda11.2.0-cudnn8/requirements.txt
  versions/cuda11.2.1-cudnn8/packages.json
  versions/cuda11.2.1-cudnn8/requirements.txt
  versions/cuda11.2.2-cudnn8/packages.json
  versions/cuda11.2.2-cudnn8/requirements.txt
  versions/cuda11.3.0-cudnn8/packages.json
  versions/cuda11.3.0-cudnn8/requirements.txt
  versions/cuda11.3.1-cudnn8/packages.json
  versions/cuda11.3.1-cudnn8/requirements.txt
  versions/cuda11.4.0-cudnn8/packages.json
  versions/cuda11.4.0-cudnn8/requirements.txt
  versions/cuda11.4.1-cudnn8/packages.json
  versions/cuda11.4.1-cudnn8/requirements.txt
  versions/cuda11.4.2-cudnn8/packages.json
  versions/cuda11.4.2-cudnn8/requirements.txt
Labels: enhancement

#47 Add config for dependabot
  .github/dependabot.yml
Labels: enhancement

#97 Update December
  .github/workflows/cuda11.2.2-cudnn8.yaml
  .github/workflows/cuda11.3.1-cudnn8.yaml
  .github/workflows/cuda11.4.0-cudnn8.yaml
  .github/workflows/cuda11.4.1-cudnn8.yaml
  .github/workflows/cuda11.4.2-cudnn8.yaml
  README.md
Labels: update
