Repository KindaiCVLAB/machinelearning-images, pull requests merged in 2022-01, with the labels that each got.

#99 Bump anaconda version to 2021.11
  versions/cuda11.2.2-cudnn8/packages.json
  versions/cuda11.3.1-cudnn8/packages.json
  versions/cuda11.4.0-cudnn8/packages.json
  versions/cuda11.4.1-cudnn8/packages.json
  versions/cuda11.4.2-cudnn8/packages.json
Labels: update

#100 Stop using pre-version libraries
  renovate.json
  versions/cuda11.4.0-cudnn8/requirements.txt
  versions/cuda11.4.1-cudnn8/requirements.txt
  versions/cuda11.4.2-cudnn8/requirements.txt
Labels: improve

#111 Add cuda11.5.0-cudnn8
  .github/workflows/build-push.yaml
  README.md
  versions/cuda11.5.0-cudnn8/packages.json
  versions/cuda11.5.0-cudnn8/requirements.txt
Labels: update

#112 Add cuda11.5.1 cudnn8
  .github/workflows/build-push.yaml
  README.md
  versions/cuda11.5.1-cudnn8/packages.json
  versions/cuda11.5.1-cudnn8/requirements.txt
Labels: cuda, update
